<?php
$this->headTitle('إضافة عضو');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Users'=>$this->url('users'),
            'Add User'=>$this->url('users', ['action'=>'add'])
            ]);

$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'name@example.com',
    'dir' => 'ltr'
    ]);

$form->get('full_name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Mhamed Mrini',
    'dir' => 'ltr'
    ]);

$form->get('username')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'abu3alae',
    'dir' => 'ltr'
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control',
    'dir' => 'ltr'
    ]);

$form->get('password')->setAttributes([
    'class'=>'form-control',
    'dir' => 'ltr'
    ]);

$form->get('confirm_password')->setAttributes([
    'class'=>'form-control',
    'dir' => 'ltr'
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$form->prepare();
?>

<h3>إضافة غضو</h3>

<p>
    من فضلك أنشئ الحقول التالية ثم إضغط زر <i><strong>إنشاء</strong></i>.
</p>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('full_name')); ?>
            <?= $this->formElement($form->get('full_name')); ?>
            <?= $this->formElementErrors($form->get('full_name')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('username')); ?>
            <?= $this->formElement($form->get('username')); ?>
            <?= $this->formElementErrors($form->get('username')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('password')); ?>
            <?= $this->formElement($form->get('password')); ?>
            <?= $this->formElementErrors($form->get('password')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('confirm_password')); ?>
            <?= $this->formElement($form->get('confirm_password')); ?>
            <?= $this->formElementErrors($form->get('confirm_password')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>                  
        </div>
        
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   

