<?php
$this->headTitle('الأعضاء');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Users'=>$this->url('users'),
            ]);
?>

<h1>إدارة الأعضاء</h1>

<p>
<a class="btn btn-default" href="
    <?= $this->url('users', ['action'=>'add']); ?>">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> عضو جديد
</a>
</p>

<table class="table table-striped">

   <tr>
        <th>ID</th>
        <th>E-mail</th>
        <th>الإسم الكامل</th>
        <th>الإسم المستعار</th>
        <th>تاريخ الإنشاء</th>
        <th>الحالة</th>        
        <th>Actions</th>        
    </tr>
    
    <?php foreach ($users as $user): ?>
    
    <tr>
        <td><?= $this->escapeHtml($user->getId()); ?></td>
        <td>
            <a href="<?= $this->url('users', ['action'=>'view', 'id'=>$user->getId()]); ?>">
                <?= $this->escapeHtml($user->getEmail()); ?>
            </a> 
        </td>
        <td><?= $this->escapeHtml($user->getFullName()); ?></a> 
        </td>
         <td><?= $this->escapeHtml($user->getUserName()); ?></td>
        <td><?= $this->escapeHtml($user->getDateCreated()); ?></td>        
        <td><?= $this->escapeHtml($user->getStatusAsString()); ?></td>
        <td>
            <a class="btn btn-info" href="<?= $this->url('users', 
                    ['action'=>'edit', 'id'=>$user->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> تعديل
            </a>
            <a class="btn btn-default" href="<?= $this->url('users',
                    ['action'=>'change-password', 'id'=>$user->getId()]); ?>">
                <span class="glyphicon glyphicon-asterisk"></span> تغيير كلمة المرور
            </a>
        </td>    
    </tr>
        
    <?php endforeach; ?>   
    
</table>

