<?php 
$this->headTitle('الكهرباء - السنة الأولى'); 
?>
<h4 class="title">الأولى إعدادي - الكهرباء</h4>
<table class="table table-striped table-hover">
    <tr><th>ترتيب الدرس</th><th>الدرس</th><th>مدة الإنجاز</th></tr>
    <?php 
    foreach ($menuItems as $menuItem) {
        echo $this->partial('college/elec1/toc', ['menuItem'=>$menuItem]);
    }
    ?>
</table>
<h4 class="title">التجارب</h4>
<table class="table table-striped table-hover">
    <tr><th>تجربة</th><th>الأهداف</th></tr>
    <tr><td>الموصلات و العوازل</td><td> التمييز بين المواد الموصلة كهربائيا و العازلة كهربائيا</td></tr>
    <tr><td>التركيب على التوالي و التركيب على التوازي‬</td><td>‬ إنجاز تراكيب كهربائية على التوالي و على التوازي</td></tr>
    <tr><td>-‬</td><td>‫‬ إبراز فائدة التركيب على التوازي</td></tr>
    <tr><td>مفهوم المقاومة الكهربائية‬</td><td>‬ قياس مقاومة كهربائية بواسطة الأومتر</td></tr>  
    <tr><td>-‬</td><td>‫‬ إبراز تأثير المقاومة على شدة التيار في دارة كهربائية</td></tr>                
    <tr><td>قانون العقد</td><td> التحقق من قانون العقد</td></tr>
    <tr><td>قانون إضافية التوترات‬</td><td> التحقق من قانون إضافية التوترات</td></tr>
    <tr><td>البحث عن العطب</td><td> معرفة كيفية الكشف عن عطب في دارة كهربائية</td></tr>
</table>

