<?php
$this->headTitle('التسجيل - المرحلة 3');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
            'الصفحة الرئيسية'=>$this->url('home'),
            'التسجيل' => $this->url('registration')
            ]);

$form->get('captcha')->setAttributes([
    'class'=>'form-control', 
    'dir' => 'ltr'
    ]);

$form->get('submit')->setAttributes(array('class'=>'btn btn-primary'));

$form->prepare();
?>

<h1>التسجل - المرحلة 3 - تصديق المعلومات</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?php echo $this->formLabel($form->get('captcha')); ?>
            <?php echo $this->formElement($form->get('captcha')); ?>
            <?php echo $this->formElementErrors($form->get('captcha')); ?>
        </div>
        
        <div class="form-group">
        <?= $this->formElement($form->get('submit')); ?>
        </div>
        
        <?= $this->formElement($form->get('csrf')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   

