<?php
$this->headTitle('التسجيل - المرحلة 1');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
            'الصفحة الرئيسية'=>$this->url('home'),
            'التسجيل' => $this->url('registration')
            ]);

$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'name@yourcompany.com',
    'dir' => 'ltr'
    ]);

$form->get('full_name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Mhamed Mrini',
    'dir' => 'ltr'
    ]);

$form->get('user_name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'abu3alae',
    'dir' => 'ltr'
    ]);

$form->get('password')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'6 characters at minimum',
    'dir' => 'ltr'
    ]);

$form->get('confirm_password')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Repeat password',
    'dir' => 'ltr'
    ]);

$form->get('submit')->setAttributes(array('class'=>'btn btn-primary'));

$form->prepare();
?>

<h1>التسجيل - المرحلة 1 - الإسم و القن</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>                              
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('full_name')); ?>
            <?= $this->formElement($form->get('full_name')); ?>
            <?= $this->formElementErrors($form->get('full_name')); ?>                              
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('user_name')); ?>
            <?= $this->formElement($form->get('user_name')); ?>
            <?= $this->formElementErrors($form->get('user_name')); ?>                              
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('password')); ?>
            <?= $this->formElement($form->get('password')); ?>
            <?= $this->formElementErrors($form->get('password')); ?>                              
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('confirm_password')); ?>
            <?= $this->formElement($form->get('confirm_password')); ?>
            <?= $this->formElementErrors($form->get('confirm_password')); ?>                              
        </div>
        
        <div class="form-group">
        <?= $this->formElement($form->get('submit')); ?>
        </div>
        
        <?= $this->formElement($form->get('csrf')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   
