<?php 
$this->headTitle('الثالثة إعدادي - المادة و البيئة'); 
?>
<h4 class="title">الثالثة إعدادي - المادة و البيئة</h4>
<table class="table table-striped table-hover">
    <tr><th>ترتيب الدرس</th><th>الدرس</th><th>مدة الإنجاز</th></tr>
    <?php 
    foreach ($menuItems as $menuItem) {
        echo $this->partial('college/matter3/toc', ['menuItem'=>$menuItem]);
    }
    ?>
</table>
<h4 class="title">التجارب</h4>
<table class="table table-striped table-hover">
    <tr><th>تجربة</th><th>الأهداف</th></tr>
    <tr><td>أكسدة الحديد بواسطة ثنائي الأكسجين</td><td> إبراز العوامل المساعدة على تأكسد الحديد في الهواء الرطب</td></tr>
    <tr><td>احتراق بعض المواد العضوية في الهواء‬</td><td> تعرف نواتج الإحتراق، و أخطاره</td></tr>
    <tr><td>‫المحاليل الحمضية و القاعدية‬</td><td>‬ تصنيف المحاليل إلى حمضية و قاعدية</td></tr>
    <tr><td>-</td><td>‫ تعرف أثر التخفيف على قيمة <span>pH</span></td></tr>
    <tr><td>تأثير المحاليل الحمضية و القاعدية على الفلزات</td><td> تعرف تأثير محلول حمض الكلوريدريك و محلول الصودا على فلزات <span>النحاس</span> و <span>الحديد</span> و <span>الزنك</span> و <span>الألومنيوم</span></td></tr>
    <tr><td>روائز الكشف عن بعض الأيونات‬</td><td> الكشف عن الأيونات الفلزية <span dir="ltr">Cu<sup>2+</sup></span> و <span dir="ltr">Fe<sup>2+</sup></span> و <span dir="ltr">Fe<sup>3+</sup></span> و <span dir="ltr">Al<sup>3+</sup></span> و <span dir="ltr">Zn<sup>2+</sup></span> .و أيون الكلورور<span dir="ltr">Cl<sup>-</sup></span></td></tr>
</table>

