<?php 
$this->headTitle('الثالثة إعدادي - الكهرباء'); 
?>
<h4 class="title">الثالثة إعدادي - الكهرباء</h4>
<table class="table table-striped table-hover">
    <tr><th>ترتيب الدرس</th><th>الدرس</th><th>مدة الإنجاز</th></tr>
    <?php 
    foreach ($menuItems as $menuItem) {
        echo $this->partial('college/elec3/toc', ['menuItem'=>$menuItem]);
    }
    ?>
</table>
<h4 class="title">التجارب</h4>
<table class="table table-striped table-hover">
    <tr><th>تجربة</th><th>الأهداف</th></tr>
    <tr><td>قانون أوم</td><td> التحقق التجريبي من قانون أوم <span>U = R x I </span></td></tr>
    <tr><td>القدرة الكهربائية‬</td><td>‬ تقديم مفهوم القدرة الكهربائية</td></tr>
    <tr><td>-</td><td>‫‬ مقارنة القدرة الكهربائية لأجهزة التسخين</td></tr>
    <tr><td>الطاقة الكهربائية</td><td>‬ تقديم مفهوم الطاقة الكهربائية</td></tr>
    <tr><td>-</td><td> مقارنة الطاقة الكهربائية المستهلكة من طرف أجهزة التسخين</td></tr>
</table>

