<?php

$this->headTitle('مراسلتنا');

$this->mainMenu()->setActiveItemId('contactus');

$this->pageBreadcrumbs()->setItems(array(
            'الصفحة الرئيسية'=>$this->url('home'),
            'مراسلتنا'=>$this->url('contactus')
            ));

$form = $this->form;
$form->setAttribute('action', $this->url('contactus'));
$form->get('email')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>'name@example.com',
    'dir' => 'ltr',
    ));
$form->get('subject')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>'الموضوع الذي تود مراسلتنا لأجله'
    ));
$form->get('body')->setAttributes(array(
    'class'=>'form-control', 
    'rows'=>6, 
    'placeholder'=>'أكتب نص رسالتك هنا'
    ));
$form->get('submit')->setAttributes(array('class'=>'btn btn-primary'));
$form->prepare();

?>

<h3>لمراسلتنا إملء الحقول التالية </h3>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <?php echo $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?php echo $this->formLabel($form->get('email')); ?>
            <?php echo $this->formElement($form->get('email')); ?>
            <?php echo $this->formElementErrors($form->get('email')); ?>                  
        </div>
        
        <div class="form-group">
            <?php echo $this->formLabel($form->get('subject')); ?>
            <?php echo $this->formElement($form->get('subject')); ?>
            <?php echo $this->formElementErrors($form->get('subject')); ?>                  
        </div>
        
        <div class="form-group">
            <?php echo $this->formLabel($form->get('body')); ?>
            <?php echo $this->formElement($form->get('body')); ?>
            <?php echo $this->formElementErrors($form->get('body')); ?>                  
        </div>
        
        <div class="form-group">
            <?php echo $this->formLabel($form->get('captcha')); ?>
            <?php echo $this->formElement($form->get('captcha')); ?>
            <?php echo $this->formElementErrors($form->get('captcha')); ?>
        </div>
        
        <?php echo $this->formElement($form->get('csrf')); ?>
        
        <?php echo $this->formElement($form->get('submit')); ?>
        
        <?php echo $this->form()->closeTag(); ?>
    </div>    
</div>    
